#!/bin/bash
#------------------------------------------
#$ -N levins_script_array
#$ -o iman.out$JOB_ID
#$ -j y
#$ -S /bin/bash
#$ -l h_rt=48:00:00 
#$ -l h_vmem=6G
#$ -pe smp 10
#$ -m 
#$ -M adam.tclark@gmail.com
#$ -t 1-7

date
module load R
cd /home/clarka/coexistence_scale/levins_metapopulation/
./iterate_spatial_scale_array.R
date
